### ISSUE TITLE
"Msisdn" is misspelled

### ISSUE THREAD

**Issue by alex-sberna** [sinch/sinch-sdk-dotnet#5]
https://github.com/sinch/sinch-sdk-dotnet/blob/0aaeb7c585e7e6110903d83310cfb3bbd681e9fd/src/Sinch/SMS/DeliveryReports/DeliveryReports.cs#L33C77-L33C78

**Comment by Dovchik** [comment]
Thanks for finding this. Will be fixed with PR #6
